In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import torch
import numpy as np
from collections import Counter
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
import math

## Additional RAM

In [ ]:
# But it is no more proposed get more RAM in a free way
[1]*10**10

## data

In [ ]:
books = "/content/drive/MyDrive/ProjetML/Base_BookCrossing/Base_completee/bothWebSites_InternetSearch_AllBooks_cleaned_w2v.csv"
ratings = "/content/drive/MyDrive/ProjetML/BX-Book-Ratings.csv"
ratings_bin = "/content/drive/MyDrive/ProjetML/BX-Book-Ratings-Binary.csv"

In [ ]:
#Cleaned data base with scrapped books
df_books = pd.read_csv(books, sep = "|")

In [ ]:
#ratings of Book Crossing
df_ratings = pd.read_csv(ratings, sep = ";", error_bad_lines=False, encoding="latin-1")

In [ ]:
print(len(df_ratings))
df_ratings.head()

1149780


User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [ ]:
df_books.head(1)

isbn       isbn_13 OtherID  ... books_in_series average_rating awards
0  0439023483  9.780439e+12     NaN  ...             NaN            NaN    NaN

[1 rows x 18 columns]

In [ ]:
df_ratings[df_ratings.ISBN == "000648302X"]

User-ID        ISBN  Book-Rating
45384      11676  000648302X            8
174443     37950  000648302X            9
373708     89624  000648302X            9
412327     98544  000648302X            0
417691     99328  000648302X            3
496961    119654  000648302X            8
499864    120610  000648302X            7
654880    158589  000648302X            8
659263    160016  000648302X            4
718973    174092  000648302X            0
769853    186024  000648302X            6
987571    237401  000648302X            3
996094    238896  000648302X            0
1117231   268056  000648302X            0

# Tests 

### Tests merge

In [ ]:
DF_CatUsers = pd.DataFrame( {"UserID": [1,1,1,2,2,3,3,3,3], 
                             "ISBN": ["ISBN1", "ISBN2", "ISBN3", "ISBN4", "ISBN5", "ISBN2", "ISBN3", "ISBN5", "ISBN6"], 
                             "Ratings": [4,5,3,2,1,4,5,4,4]})
DF_CatUsers

In [ ]:
DF_CatBooks = pd.DataFrame( {"ISBN": ["ISBN1", "ISBN2", "ISBN3", "ISBN4", "ISBN5", "ISBN6", "ISBN7", "ISBN8"], 
                             "features": ["Blabla1", "Blabla2", "Blabla3", "Blabla4", "Blabla5", "Blabla6", "Blabla7", "Blabla8"]})
DF_CatBooks

In [ ]:
pd.merge(DF_CatUsers, DF_CatBooks, on = "ISBN")

### Test descriptions

In [ ]:
for d in df_books["book_description"][:3]:
    print(d)

# Bert on books descriptions (already trained)

### Loading

In [ ]:
!pip install transformers

     |████████████████████████████████| 2.3MB 28.1MB/s 
     |████████████████████████████████| 901kB 57.1MB/s 
     |████████████████████████████████| 3.3MB 49.6MB/s 


In [ ]:
from transformers import BertTokenizer, BertModel

In [ ]:
#I will use an already trained BERT network
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

### Tokenizer and embedding

In [ ]:
#Use of pretrained model
# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-uncased',
                                  output_hidden_states = True, # Whether the model returns all hidden-states.
                                  )

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
model.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [ ]:
#With use of GPU I will save lots of time
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model.to(device)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [ ]:
sent_list = df_bert.book_description[100].split(".")
sent_list = [sent for sent in sent_list if len(sent) > 3]
print(len(sent_list))
[sent for sent in sent_list if len(sent) > 3]

2


['This gripping tale unfolds in a peaceful Minnesota town, where crime is something that just doesn&#39;t happen',
 ' But when a young boy disappears, it marks the beginning of a unspeakable nightmare']

In [ ]:
"bonjour il n'y a pas de point".split(".")

["bonjour il n'y a pas de point"]

In [ ]:
df_bert = df_books.copy()

In [ ]:
lineOK = df_bert[(df_bert["book_description"].isna() == False) & (df_bert["book_language"] == "en")]
len(lineOK)

64229

In [ ]:
#Creation of an additional column in order to put the future book_description embedding
df_bert = df_bert.assign(description_bert = 0)

In [ ]:
#execution in about 16min

#from transformers import BertTokenizer
#tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

#model = BertModel.from_pretrained('bert-base-uncased'...
#forward(input_ids=None, attention_mask=None, ...

with torch.no_grad():
  for i_line in lineOK.index:
    
    #one book description, potentially composed of several sentences
    sent_list = df_bert.book_description[i_line].split(".")
    #I only keep the not empty results of the previous split
    sent_list = [sent for sent in sent_list if len(sent) > 3]

    #Output of sentences tokenization
    input_ids = []
    attention_masks = []

    #For each english sentence in the current book_description (not empty)
    ######################
    # Tokenization
    ######################
    for sent in sent_list:

      #print(len(sent.split()))
      #Tokenize all of the sentences and map the tokens to thier word IDs.
      encoded_dict = tokenizer.encode_plus(
                                  sent,                      # Sentence to encode.
                                  add_special_tokens = True, # Add '[CLS]' and '[SEP]'
                                  max_length = 64,           # Pad & truncate all sentences.
                                  pad_to_max_length = True,
                                  return_attention_mask = True,   # Construct attn. masks.
                                  return_tensors = 'pt',     # Return pytorch tensors.
                        )
              
      # Add the encoded sentence to the list.    
      input_ids.append(encoded_dict['input_ids'])
              
      # And its attention mask (simply differentiates padding from non-padding).
      attention_masks.append(encoded_dict['attention_mask'])

    ######################
    # Embeddings
    ######################
    if (len(input_ids) > 0):
      # Convert the lists into tensors.
      input_ids_t = torch.cat(input_ids, dim = 0)
      attention_masks_t = torch.cat(attention_masks, dim = 0)

      #use Bert to embedds each tokenized sentences of the current book_description
      outputs = model(input_ids_t.to(device), attention_masks_t.to(device))
      hidden_states = outputs[2]

      # `hidden_states`       has shape [13 layers, len(input_ids), 64, 768] 
      # => hidden_states[-2]  has shape [len(input_ids), 64, 768] 
      token_vecs = hidden_states[-2]
      #print(token_vecs.shape)

      #mean elements by elements of each token (64 tokens in total) of each embedded sentences of the current book_description
      #=> sentence_embedding  has shape [len(input_ids), 768]: 
      sentence_embedding = torch.mean(token_vecs, dim=1)
      #print(sentence_embedding.shape)

      #I only want to keep one embedding of dim 768 for each book_description
      #(and not len(input_ids) x 768)
      sentence_embedding = torch.mean(sentence_embedding, dim=0)
      #print(sentence_embedding.size())


      ######################
      # Saving
      ######################
      #I get the values from GPU, and I put it in df_bert.description_bert column
      sentence_embedding = sentence_embedding.cpu().numpy()
      l = len(sentence_embedding)
      df_bert.description_bert[i_line] = [str(sentence_embedding[i]) for i in range(l)]


/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2110: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:78: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats i

In [ ]:
# Print sentence 0, now as a list of IDs.
print('Original: ', df_bert.book_description[lineOK.index[0]])
print('Token IDs:', df_bert.description_bert[lineOK.index[0]])

Original:  With 160 million copies of the Twilight Saga sold worldwide, this addictive love story between a teenage girl and a vampire redefined romance for a generation. Here&#39;s the book that started it all.
Token IDs: ['-0.098250076', '-0.38007897', '0.8143984', '-0.069222644', '0.16267884', '-0.36887923', '0.09200936', '0.4111976', '0.32065162', '-0.0675951', '-0.17918313', '-0.24016543', '0.19495136', '0.4354491', '0.41287875', '0.4453775', '-0.24839687', '0.16070387', '0.14195046', '-0.16554643', '0.30131242', '0.28766793', '-0.12406763', '0.17628828', '0.21566428', '0.37729064', '-0.3119564', '0.008895561', '-0.51559365', '0.3141598', '0.25739694', '-0.24879043', '0.24140932', '0.0896724', '-0.38097662', '-0.012144949', '-0.15168047', '0.021698063', '-0.23981865', '0.23302785', '-0.5429584', '-0.34142113', '0.39717984', '-0.47054458', '-0.12300413', '-0.014472974', '0.20256266', '0.048919663', '-0.06945287', '-0.14903395', '-0.48877', '-0.08599328', '0.078301966', '-0.1906274'

In [ ]:
df_bert.to_csv("/content/drive/MyDrive/ProjetML/Books_description_bert.csv", sep = "|", index = False)

# Fast Text on books descriptions


### Sentences tokenized

In [ ]:
import re
import nltk

from nltk.stem import PorterStemmer
ps = PorterStemmer()

from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords_list = stopwords.words('english')

from nltk import WordPunctTokenizer
word_punctuation_tokenizer = nltk.WordPunctTokenizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
def preprocess_text(document):
        # Remove all the special characters
        document = re.sub(r'\W', ' ', str(document))

        # remove all single characters
        document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)

        # Remove single characters from the start
        document = re.sub(r'\^[a-zA-Z]\s+', ' ', document)

        # Substituting multiple spaces with single space
        document = re.sub(r'\s+', ' ', document, flags=re.I)

        # Removing prefixed 'b'
        document = re.sub(r'^b\s+', '', document)

        # Converting to Lowercase
        document = document.lower()

        # Lemmatization
        tokens = document.split()
        tokens = [ps.stem(word) for word in tokens]
        tokens = [word for word in tokens if word not in stopwords_list]
        tokens = [word for word in tokens if len(word) > 3]

        preprocessed_text = ' '.join(tokens)

        return preprocessed_text

In [ ]:
#We only use the not empty book_description lines, and english books
lineOK = df_books[(df_books["book_description"].isna() == False) & (df_books["book_language"] == "en")]
len(lineOK)

64229

In [ ]:
print(len(lineOK))
df_books.book_description[lineOK.index[0]]

64229


'With 160 million copies of the Twilight Saga sold worldwide, this addictive love story between a teenage girl and a vampire redefined romance for a generation. Here&#39;s the book that started it all.'

In [ ]:
df_books.book_description[lineOK.index[1]]

'Bestselling author John Green returns with an eagerly anticipated and emotional novel about sickness and health, life and death.'

In [ ]:
#list of all sentences
final_corpus = []

for i_line in lineOK.index:
    
  #one book description, potentially composed of several sentences
  sent_list = df_books.book_description[i_line].split(".")

  #for each sub-sentences of the description: tokenization
  cleaned_sent = [preprocess_text(sent) for sent in sent_list if sent.strip() !='']

  #for each tokenized sub-sentences, a last cleaning
  word_tokenized_corpus = []
  for sent in cleaned_sent:
    word_tokenized_corpus.extend(word_punctuation_tokenizer.tokenize(sent))

  #only one list for all sub-sentences of the same book's description
  final_corpus.append(word_tokenized_corpus)


In [ ]:
cleaned_sent

['bestsel author john green return eagerli anticip emot novel sick health life death']

In [ ]:
final_corpus

[['million',
  'copi',
  'twilight',
  'saga',
  'sold',
  'worldwid',
  'addict',
  'love',
  'stori',
  'teenag',
  'girl',
  'vampir',
  'redefin',
  'romanc',
  'gener',
  'book',
  'start'],
 ['bestsel',
  'author',
  'john',
  'green',
  'return',
  'eagerli',
  'anticip',
  'emot',
  'novel',
  'sick',
  'health',
  'life',
  'death']]

In [ ]:
len(final_corpus)

64229

### Training

In [ ]:
from gensim.models.fasttext import FastText

In [ ]:
embedding_size = 60
window_size = 40
min_word = 1
down_sampling = 1e-2

In [ ]:
#It takes about 1H 10min for about 65 000 lines

# window_size :
#       is the size of the number of words occurring before and after 
#       the word based on which the word representations will be learned for the word.

#min_word :
#       which specifies the minimum frequency of a word in the corpus 
#       for which the word representations will be generated.

#sg :
#       A value of 1 specifies that we want to create skip-gram model.

ft_model = FastText(final_corpus,
                      size      = embedding_size,
                      window    = window_size,
                      min_count = min_word,
                      sample    = down_sampling,
                      sg        = 1,
                      iter      = 100)

In [ ]:
ft_model.save("/content/drive/MyDrive/ProjetML/FastText_desc.model")

### Save of embeddings

In [ ]:
ft_model = FastText.load("/content/drive/MyDrive/ProjetML/FastText_desc.model")

In [ ]:
df_fastFM = df_books.copy()

#Creation of an additional column in order to put the future book_description embedding
df_fastFM = df_fastFM.assign(description_fastFM = 0)

lineOK = df_books[(df_books["book_description"].isna() == False) & (df_books["book_language"] == "en")]
len(lineOK)

64229

In [ ]:
df_fastFM.head(1)

isbn       isbn_13 OtherID  ... average_rating awards description_fastFM
0  0439023483  9.780439e+12     NaN  ...            NaN    NaN                  0

[1 rows x 19 columns]

In [ ]:
for i in range(len(lineOK.index)):

  #a tokenized sentences
  sent = final_corpus[i]
  #print("len(sent)", len(sent))

  if (len(sent) > 0):
    #find the embedding (vector of 60) for all words inside tokenized sentence
    words_emb = [ft_model.wv[w] for w in sent]
    #print(words_emb, len(words_emb))

    emb = [0.0]*60

    #Perform the sum of each words embeddings
    for word in words_emb:
      l = len(word)
      #sum of embedding of each words
      #print("\n", l, "\n", word)
      emb = [emb[k] + word[k] for k in range(l)]
      #print(emb)

    #print("emb", emb)
    #print("len(words_emb)", len(words_emb))
    emb = [emb[k] / len(words_emb) for k in range(l)]
    #print("emb", emb)  

    # Saving
    df_fastFM.description_fastFM[lineOK.index[i]] = [str(emb[i]) for i in range(l)]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [ ]:
 [str(emb[i]) for i in range(l)]

['-0.015599380892056685',
 '0.34733651177241254',
 '-0.20130442784955868',
 '-0.254810130653473',
 '-0.0017622755840420723',
 '-0.17762010401258102',
 '-0.00482538715004921',
 '0.22535292173807436',
 '-0.01569059620109888',
 '0.04152290172462996',
 '-0.08608597660293946',
 '0.08708254095668402',
 '0.12789110868022993',
 '0.21732267533214047',
 '-0.2619647120053952',
 '-0.07633995605059542',
 '0.0036140303485668623',
 '-0.06340917027913608',
 '-0.027962678470290624',
 '-0.16541503068919367',
 '0.24956483608828142',
 '0.15758277624487305',
 '0.09344531438098504',
 '-0.012878868299034925',
 '0.03124704022103777',
 '-0.032272872156821765',
 '-0.1944929759662885',
 '-0.13054967041199023',
 '-0.3048797926077476',
 '-0.1617659333591851',
 '0.16737894513286078',
 '-0.16401336417318538',
 '0.29739678077972853',
 '-0.23934618956767595',
 '0.19287096021267083',
 '-0.26317760806817275',
 '-0.1648963175069254',
 '-0.10843969938846734',
 '0.010802279871243697',
 '0.33178424104475057',
 '0.0498662182

In [ ]:
# Print sentence 0, now as a list of IDs.
print('Original: ', df_fastFM.book_description[lineOK.index[0]])
print('Token IDs:', df_fastFM.description_fastFM[lineOK.index[0]])

Original:  With 160 million copies of the Twilight Saga sold worldwide, this addictive love story between a teenage girl and a vampire redefined romance for a generation. Here&#39;s the book that started it all.
Token IDs: ['0.046032028402859235', '0.15718470524777384', '-0.1395825319649542', '-0.1819172301055754', '0.17207935299066937', '-0.1365122384775211', '0.16689892704872525', '0.33930738577071357', '-0.06989275658612742', '0.31512450802085157', '-0.10388041380792856', '0.022007644121699473', '1.6696477199302e-05', '0.3797191175467828', '-0.273707770742476', '-0.20886098593473434', '0.11984747141490087', '-0.10271839490708183', '-0.09797142072142485', '-0.23660339820472634', '0.2803903391913456', '0.11936031935757081', '0.024216600488323498', '0.0775216789368321', '-0.014470523113713545', '-0.09681690356913297', '-0.09977425330811564', '0.1142483646159663', '-0.2905912635957493', '0.026502975954345483', '0.2798446424524574', '-0.09337197529042468', '0.21702254563570023', '-0.1523

In [ ]:
df_fastFM.to_csv("/content/drive/MyDrive/ProjetML/Books_description_fastText.csv", sep = "|", index = False)

# Fast Text on AuthorContext
- book_title 
- book_author 
- Category 
- Category_other 
- author_genres 
- author_genres_other

### Information preparation

In [ ]:
#We keep only few columns to create the context of training
df1 = df_books[df_books["book_language"] == "en"]
df1 = df1[["book_title", "book_author", "Category", "Category_other", "author_genres", "author_genres_other"]]
print(len(df_books))
print(len(df1))
df1[1000:1005]

105508
93808


book_title  ... author_genres_other
1010               Shadowland : The Immortals  ...                 NaN
1011                   You Can Heal Your Life  ...             spiritu
1013                              I Am Legend  ...             fantasi
1014                            Rules of Prey  ...            thriller
1015  The Yiddish Policemen's Union : A Novel  ...             fiction

[5 rows x 6 columns]

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords_list = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#with data set of about 100 000 lines, it takes 1 min
lines_OK = df1.book_title[df1.book_title.isna() == False]

for i in lines_OK.index:
    #we get sentence inside book_title column, we remove final '.' and separate all words
    w = df1.book_title[i].strip('.').split()

    #we remove stopwords, words of length < 2 and '...'
    ww = [word.strip(',') for word in w if (word not in stopwords_list) and len(word) > 2 and (word != '...')]

    #We reconstruct a sentence with the remaining words, separated with ','
    df1.book_title[i] = ','.join(ww)

In [ ]:
print(len(df1))
df1.book_title.head()

93808


0    The,Hunger,Games,The,First,Book,Hunger,Games
1                                        Twilight
2                             The,Fault,Our,Stars
3                                   Angels,Demons
4                                       Divergent
Name: book_title, dtype: object

In [ ]:
#All those columns informations must be joined inside one column
#str(x) != "nan":     but we join only if column word is not empty
#x.split():           sentences in colum 'book_title' are cut in words
#','.join(x.split()): all those words are joined with (',') to be transformed after in list of list
def WordToJoin(w):
  ww = [x for x in w if str(x) != "nan"]
  return ','.join(ww)

df2 = df1.apply(lambda x: WordToJoin(x), axis = 1)
df2.head()

0    The,Hunger,Games,The,First,Book,Hunger,Games,S...
1    Twilight,Stephenie Meyer,young adult fict,scie...
2    The,Fault,Our,Stars,John Green,juvenile fict,l...
3     Angels,Demons,Dan Brown,fiction,mysteri,thriller
4    Divergent,Veronica Roth,juvenile fict,science ...
dtype: object

In [ ]:
#a specific data frame is created with all this train context
df_clean = pd.DataFrame({'clean': df2})
df_clean.head()

clean
0  The,Hunger,Games,The,First,Book,Hunger,Games,S...
1  Twilight,Stephenie Meyer,young adult fict,scie...
2  The,Fault,Our,Stars,John Green,juvenile fict,l...
3   Angels,Demons,Dan Brown,fiction,mysteri,thriller
4  Divergent,Veronica Roth,juvenile fict,science ...

In [ ]:
#list of lists creation: 1 list for each book
sent = [' '.join(row.split(',')) for row in df_clean['clean']]
print(len(sent))
sent[0]

93808


'The Hunger Games The First Book Hunger Games Suzanne Collins juvenile fict'

### Training

In [ ]:
from gensim.models.fasttext import FastText

In [ ]:
embedding_size = 60
window_size = 40
min_word = 1
down_sampling = 1e-2

In [ ]:
#It takes about almost 4 Hours for about 105 000 lines

# window_size :
#       is the size of the number of words occurring before and after 
#       the word based on which the word representations will be learned for the word.

#min_word :
#       which specifies the minimum frequency of a word in the corpus 
#       for which the word representations will be generated.

#sg :
#       A value of 1 specifies that we want to create skip-gram model.

ft_model_auth = FastText(sent,
                      size      = embedding_size,
                      window    = window_size,
                      min_count = min_word,
                      sample    = down_sampling,
                      sg        = 1,
                      iter      = 100)

In [ ]:
ft_model_auth.save("/content/drive/MyDrive/ProjetML/FastText_auth.model")

### Save of embeddings

In [ ]:
ft_model_auth = FastText.load("/content/drive/MyDrive/ProjetML/FastText_auth.model")

In [ ]:
df_fastText_auth = df_books.copy()

#Creation of an additional column in order to put the future book_description embedding
df_fastText_auth = df_fastText_auth.assign(authorsContext_fastText = 0)

lineOK = df_fastText_auth[df_fastText_auth["book_language"] == "en"]
len(lineOK)

In [ ]:
print(len(df_fastText_auth))
print(len(sent))
df_fastText_auth.head(3)

105508
105508


isbn  ...  authorsContext_fastText
0  0439023483  ...                        0
1  0316015849  ...                        0
2  0525478817  ...                        0

[3 rows x 19 columns]

In [ ]:
df_fastText_auth.authorsContext_fastText[1]

0

In [ ]:
for i in range(len(lineOK.index)):

  #a tokenized sentences
  sent_auth = sent[i]
  #print("len(sent)", len(sent))

  if (len(sent_auth) > 0):
    #find the embedding (vector of 60) for all words inside tokenized sentence
    words_emb = [ft_model_auth.wv[w] for w in sent_auth]

    emb = [0.0]*60

    #Perform the sum of each words embeddings
    for word in words_emb:
      l = len(word)
      #sum of embedding of each words
      emb = [emb[k] + word[k] for k in range(l)]

    emb = [emb[k] / len(words_emb) for k in range(l)]

    # Saving
    df_fastText_auth.authorsContext_fastText[lineOK.index[i]] = [str(emb[i]) for i in range(l)]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


In [ ]:
# Print sentence 0, now as a list of IDs.
print('Original: ', df_fastText_auth.book_title[lineOK.index[0]])
print('Token IDs:', df_fastText_auth.authorsContext_fastText[lineOK.index[0]])

In [ ]:
df_fastText_auth.to_csv("/content/drive/MyDrive/ProjetML/authorsContext_fastText.csv", sep = "|", index = False)

# Binary ratings

In [ ]:
#ratings of Book Crossing
df_ratings = pd.read_csv(ratings, sep = ";", error_bad_lines=False, encoding="latin-1")
print(len(df_ratings))
df_ratings.head(1)

1149780


User-ID        ISBN  Book-Rating
0   276725  034545104X            0

In [ ]:
df_BinRatings = df_ratings.copy()
df_BinRatings["Book-Rating"].value_counts(sort = False )

0     716109
1       1770
2       2759
3       5996
4       8904
5      50974
6      36924
7      76457
8     103736
9      67541
10     78610
Name: Book-Rating, dtype: int64

In [ ]:
#Value 0 are put to 15 in order to be treated separately
#Then the two binary classes are created :
# 1, 2, 3 and 4 ratings become 0
# 7, 8, 9 and 10 ratings become 1

#Then a part of 0 previous rating will be used to balance the binary classes
#307000 lines of separated 15 values will be taken in random order to fill the binary classe 0
df_BinRatings["Book-Rating"] = df_BinRatings["Book-Rating"].map({0: 15, 1: 0, 2: 0, 3: 0, 4: 0, 7: 1, 8: 1, 9: 1, 10: 1})
df_BinRatings["Book-Rating"].value_counts(sort = False)

0.0      19429
15.0    716109
1.0     326344
Name: Book-Rating, dtype: int64

In [ ]:
#Values 15 (old 0 values) are selected...
df_BinRatings15 = df_BinRatings[df_BinRatings["Book-Rating"] == 15]
print(len(df_BinRatings15))
df_BinRatings15.head()

716109


User-ID        ISBN  Book-Rating
0    276725  034545104X         15.0
2    276727  0446520802         15.0
5    276733  2080674722         15.0
10   276746  0425115801         15.0
11   276746  0449006522         15.0

In [ ]:
#... and put in random order
df_BinRatings15 = df_BinRatings15.sample(frac = 1, random_state=10).reset_index(drop = True)
print(len(df_BinRatings15))
df_BinRatings15.head()

716109


User-ID        ISBN  Book-Rating
0   265202  0385471548         15.0
1    78974  8420400963         15.0
2   190807  0671042475         15.0
3   252695  0843950757         15.0
4   190708  044015393X         15.0

In [ ]:
#then only the first 307000 lines are kept in order to balance our future binary classes
df_BinRatings15 = df_BinRatings15[:307000]
print(len(df_BinRatings15))
df_BinRatings15.head()

307000


User-ID        ISBN  Book-Rating
0   265202  0385471548         15.0
1    78974  8420400963         15.0
2   190807  0671042475         15.0
3   252695  0843950757         15.0
4   190708  044015393X         15.0

In [ ]:
#Then initial values 0 are put again
df_BinRatings15["Book-Rating"] = df_BinRatings15["Book-Rating"].map({15: 0})
print(len(df_BinRatings15))
df_BinRatings15.head()

307000


User-ID        ISBN  Book-Rating
0   265202  0385471548            0
1    78974  8420400963            0
2   190807  0671042475            0
3   252695  0843950757            0
4   190708  044015393X            0

In [ ]:
#know we will concatenate new 0 classe...
df_BinRatings0 = df_BinRatings[df_BinRatings["Book-Rating"] == 0]
print(len(df_BinRatings0))
df_BinRatings0.head()

19429


User-ID         ISBN  Book-Rating
3     276729   052165615X          0.0
49    276762   3453213025          0.0
55    276762  N3453124715          0.0
57    276768   9057868059          0.0
241   276853   8420457477          0.0

In [ ]:
#...with new 1 classe...
df_BinRatings1 = df_BinRatings[df_BinRatings["Book-Rating"] == 1]
print(len(df_BinRatings1))
df_BinRatings1.head()

326344


User-ID        ISBN  Book-Rating
6    276736  3257224281          1.0
8    276744  038550120X          1.0
9    276745   342310538          1.0
16   276747  0060517794          1.0
19   276747  0671537458          1.0

In [ ]:
#...and with previous treated 0 values
df_ratings_new = pd.concat([df_BinRatings15, df_BinRatings0, df_BinRatings1], ignore_index = True, axis = 0)	
print(len(df_ratings_new))
df_ratings_new.head()

652773


User-ID        ISBN  Book-Rating
0   265202  0385471548          0.0
1    78974  8420400963          0.0
2   190807  0671042475          0.0
3   252695  0843950757          0.0
4   190708  044015393X          0.0

In [ ]:
df_ratings_new["Book-Rating"].value_counts(sort = False )

0.0    326429
1.0    326344
Name: Book-Rating, dtype: int64

In [ ]:
df_ratings_new.to_csv("/content/drive/MyDrive/ProjetML/BX-Book-Ratings-Binary.csv", sep = "|", index = False)

# Ordinal regression

### Train / Test data creation

##### DF loadings

In [ ]:
#My_embedding = "bert"
#My_embedding = "fastText"
My_embedding = "fastText_auth"

In [ ]:
#We get the bert embedding of book_description 
if (My_embedding == "bert"):
  df_bert = pd.read_csv("/content/drive/MyDrive/ProjetML/Books_description_bert.csv", sep = "|")
  print(len(df_bert))

if (My_embedding == "fastText"):
  df_fastText = pd.read_csv("/content/drive/MyDrive/ProjetML/Books_description_fastText.csv", sep = "|")
  print(len(df_fastText))

if (My_embedding == "fastText_auth"):
  df_fastText_auth = pd.read_csv("/content/drive/MyDrive/ProjetML/authorsContext_fastText.csv", sep = "|")    
  print(len(df_fastText_auth))


105508


##### Merge

In [ ]:
#ratings of Book Crossing
#df_ratings = pd.read_csv(ratings, sep = ";", error_bad_lines=False, encoding="latin-1")
df_ratings = pd.read_csv(ratings_bin, sep = "|", error_bad_lines=False, encoding="latin-1")

print(len(df_ratings))
df_ratings.head(1)

652773


User-ID        ISBN  Book-Rating
0   265202  0385471548          0.0

In [ ]:
#Join of ratings and books data base, according to ISBN which is a common column

if (My_embedding == "bert"):
  df_bert = pd.merge(df_ratings, df_bert, left_on = "ISBN", right_on = "isbn")  
  print(len(df_bert))
  
  #We only use the not empty book_description lines, and english books
  lineOK = df_bert[(df_bert["book_description"].isna() == False) & \
                   (df_bert["book_language"] == "en") & \
                   (df_bert["description_bert"] != '0')]
  print(len(lineOK))

if (My_embedding == "fastText"):
  df_fastText = pd.merge(df_ratings, df_fastText, left_on = "ISBN", right_on = "isbn")  
  print(len(df_fastText))

  #We only use the not empty book_description lines, and english books
  lineOK = df_fastText[(df_fastText["book_description"].isna() == False) & \
                       (df_fastText["book_language"] == "en") & \
                       (df_fastText["description_fastFM"] != '0')]
  print(len(lineOK))

if (My_embedding == "fastText_auth"):
  df_fastText_auth = pd.merge(df_ratings, df_fastText_auth, left_on = "ISBN", right_on = "isbn")  
  print(len(df_fastText_auth))

  #We only use the english books
  lineOK = df_fastText_auth[(df_fastText_auth["book_language"] == "en") & \
                            (df_fastText_auth["authorsContext_fastText"] != '0')]
  print(len(lineOK))

64148
47787


##### Columns selection

In [ ]:
if (My_embedding == "bert"):
  X_data = df_bert[["User-ID", "description_bert"]]

if (My_embedding == "fastText"):
  X_data = df_fastText[["User-ID", "description_fastFM"]]

if (My_embedding == "fastText_auth"):
  X_data = df_fastText_auth[["User-ID", "authorsContext_fastText"]]

X_data.head()

User-ID                            authorsContext_fastText
0   190708  ['-0.11191713949665427', '-0.08290330194202918...
1   116599  ['-0.10984325339086354', '-0.08295069307088852...
2   172030  ['-0.10984325339086354', '-0.08295069307088852...
3   179733  ['-0.10984325339086354', '-0.08295069307088852...
4   107784  ['-0.10984325339086354', '-0.08295069307088852...

In [ ]:
X_data.iloc[1]

User-ID                                                               116599
authorsContext_fastText    ['-0.10984325339086354', '-0.08295069307088852...
Name: 1, dtype: object

##### Strings of embeddings transformed into float

In [ ]:
if (My_embedding == "bert"):
  s = 768
  MIN = min(df_bert["User-ID"])
  MAX = max(df_bert["User-ID"])
  print("min:", MIN)
  print("max:", MAX)

if (My_embedding == "fastText"):
  s = 60
  MIN = min(df_fastText["User-ID"])
  MAX = max(df_fastText["User-ID"])
  print("min:", MIN)
  print("max:", MAX)

if (My_embedding == "fastText_auth"):
  s = 60
  MIN = min(df_fastText_auth["User-ID"])
  MAX = max(df_fastText_auth["User-ID"])
  print("min:", MIN)
  print("max:", MAX)

min: 8
max: 278854


In [ ]:
#Transformation of a X_data line into a vector 
#beacause bert embedding has been saved as a list of strings
def vectBertfastText(l, s):

  #print(l, s)
  #for example bert embedding of s = 768 and User-ID
  b = np.zeros(s+1)

  #1st copy of User-ID
  b[0] = (l[0]-MIN)/(MAX-MIN)

  #Then handling of list of strings
  v = l[1].split("'")
  b[1:] = [float(v[i]) for i in range(1, len(v), 2)]
  
  return b

In [ ]:
res = vectBertfastText(X_data.iloc[1], s)
print("\n", len(res))
res[0:5]


 61


array([ 0.41811968, -0.10984325, -0.08295069, -0.05409687, -0.12666675])

In [ ]:
#treatment of all lines of X_data such that X_data.book_description is not empty
def matBertfastText(l, s, df):

  #for example bert embedding of s = 768 and User-ID
  m = np.zeros((len(l), (s+1)))
  
  ind = 0
  for i in l.index:
      #print(df.iloc[i])
      m[ind] = vectBertfastText(df.iloc[i], s)
      ind = ind + 1
  
  return m

In [ ]:
#It takes about 1min for about 75 000 lines
mat_X_data = matBertfastText(lineOK, s, X_data)
mat_X_data.shape

(47787, 61)

##### Labels lines selection

In [ ]:
if (My_embedding == "bert"):
  Y_data = df_bert["Book-Rating"]

if (My_embedding == "fastText"): 
  Y_data = df_fastText["Book-Rating"] 

if (My_embedding == "fastText_auth"): 
  Y_data = df_fastText_auth["Book-Rating"] 

Y_data.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Book-Rating, dtype: float64

In [ ]:
#treatment of all corresponding lines of Y_data
#=> same lines as lines for which X_data.book_description is not empty
def vectLabels(l, df):
  m = np.zeros((len(l), 1), dtype = int)
  
  ind = 0
  for i in l.index:
      m[ind] = df.iloc[i]
      ind = ind + 1
  
  return m

In [ ]:
vect_Y_data = vectLabels(lineOK, Y_data)
vect_Y_data.shape

(47787, 1)

##### Train / Test split

In [ ]:
(X_train, X_test, y_train, y_test) = train_test_split(mat_X_data, vect_Y_data,          
                                           test_size=.2, stratify = vect_Y_data)

In [ ]:
print("len(lineOK)", len(lineOK), "\n")

print("X_train.shape", X_train.shape)
print("X_test.shape", X_test.shape, "\n")

print("y_train.shape", y_train.shape)
print("y_test.shape", y_test.shape)

len(lineOK) 47787 

X_train.shape (38229, 61)
X_test.shape (9558, 61) 

y_train.shape (38229, 1)
y_test.shape (9558, 1)


### Model training

##### Loading

In [ ]:
!pip install mord
from mord import LogisticAT, OrdinalRidge

  Created wheel for mord: filename=mord-0.6-cp37-none-any.whl size=6007 sha256=7721dfba7b638e492198a874980a1616adb8cec5ae1ba1890faaaee9621888c7
  Stored in directory: /root/.cache/pip/wheels/98/14/b2/244c2cec93a0c6edb29b488bd6b2710ded7e9d457033b86366
Successfully built mord


In [ ]:
LogisticAT().get_params().keys()

dict_keys(['alpha', 'max_iter', 'verbose'])

In [ ]:
np.logspace(3, 5, 5)

array([  1000.        ,   3162.27766017,  10000.        ,  31622.77660168,
       100000.        ])

In [ ]:
dico_param = {
    'max_iter': np.logspace(3, 5, 5).astype(int),
    'alpha': np.logspace(0, 4, 5)
}

recherche_hyper = GridSearchCV(estimator = LogisticAT(), \
			param_grid = dico_param, scoring="accuracy", cv=5)

##### Unbalanced ratings

In [ ]:
X_train[0:5]

array([[ 0.84211357, -0.29635215,  0.01316709, ...,  0.11848863,
         0.06767045,  0.00823069],
       [ 0.51428746, -0.43689385, -0.01185835, ..., -0.09898453,
         0.00223271,  0.07316232],
       [ 0.75070469, -0.5633658 , -0.05594178, ..., -0.07101034,
         0.30207002,  0.17361295],
       [ 0.60774765,  0.24438658,  0.10958102, ..., -0.54591143,
         0.13632047, -0.2046924 ],
       [ 0.64970629, -0.14233115,  0.10107196, ..., -0.3077434 ,
         0.03915694,  0.02166758]])

In [ ]:
Counter(np.squeeze(y_train))

Counter({0: 31513,
         1: 70,
         2: 118,
         3: 272,
         4: 385,
         5: 2137,
         6: 1550,
         7: 3306,
         8: 4639,
         9: 2878,
         10: 3743})

In [ ]:
#It takes about 7 to 14 min 
LAT = LogisticAT(alpha=0., max_iter = 10000)
LAT.fit(X_train, np.squeeze(y_train))

ORD = OrdinalRidge(alpha=0., max_iter = 10000)
ORD.fit(X_train, np.squeeze(y_train))

OrdinalRidge(alpha=0.0, copy_X=True, fit_intercept=True, max_iter=10000,
             normalize=False, random_state=None, solver='auto', tol=0.001)

In [ ]:
#It takes about 20min
recherche_hyper.fit(X_train, np.squeeze(y_train))

GridSearchCV(cv=5, error_score=nan,
             estimator=LogisticAT(alpha=1.0, max_iter=1000, verbose=0),
             iid='deprecated', n_jobs=None,
             param_grid={'alpha': array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04]),
                         'max_iter': array([  1000,   3162,  10000,  31622, 100000])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

##### Binary ratings

In [ ]:
X_train[0:5]

array([[ 1.60371675e-01, -1.26238594e-01, -8.32735107e-02,
        -5.82985954e-02, -1.33852799e-01, -4.89134927e-02,
         1.84998448e-01,  6.63132792e-03,  1.48151493e-01,
         1.50749634e-02, -1.29045514e-03,  6.93526752e-03,
         1.09809046e-01, -4.49881596e-02, -2.53374683e-02,
         1.07558615e-01, -7.29901298e-02,  3.05418173e-03,
         2.77515438e-02,  1.22978088e-02,  4.73153767e-02,
         1.14596972e-01,  2.93340122e-02,  1.19162422e-02,
        -2.97893321e-03, -9.75541255e-02,  8.54812186e-02,
         1.53269891e-01,  6.01950713e-02, -5.24735597e-03,
         2.68517337e-02,  4.11020742e-02, -1.83939777e-02,
         2.12418386e-02, -9.77336070e-02,  3.28873654e-04,
         3.74071443e-02,  1.30226272e-01,  7.14016394e-03,
         1.08716329e-04, -1.94958644e-02,  2.35171679e-01,
         4.21229458e-02, -5.06223058e-02,  6.69311090e-02,
        -5.15372402e-02, -1.11727803e-02, -4.63990273e-02,
        -1.94347313e-02, -3.95717161e-03,  7.25962818e-0

In [ ]:
Counter(np.squeeze(y_train))

Counter({0: 18763, 1: 19466})

In [ ]:
#It takes about 7 to 14 min 
LAT = LogisticAT(alpha=0., max_iter = 10000)
LAT.fit(X_train, np.squeeze(y_train))

ORD = OrdinalRidge(alpha=0., max_iter = 10000)
ORD.fit(X_train, np.squeeze(y_train))

OrdinalRidge(alpha=0.0, copy_X=True, fit_intercept=True, max_iter=10000,
             normalize=False, random_state=None, solver='auto', tol=0.001)

### Model validation

##### Unbalanced ratings

In [ ]:
X_test[0:5]

array([[ 0.19066438, -0.435901  ,  0.06986149, ..., -0.20865309,
         0.2003329 , -0.00514526],
       [ 0.84310695, -0.55322945, -0.38845336, ...,  0.03509996,
         0.3275683 ,  0.01004667],
       [ 0.5914304 , -0.30207   , -0.20597611, ...,  0.00426296,
         0.11963355,  0.09201454],
       [ 0.24825172, -0.55261505, -0.5246434 , ...,  0.09019524,
        -0.07940055, -0.06975325],
       [ 0.44902563,  0.1674763 ,  0.26692438, ..., -0.30544358,
        -0.08587246,  0.31044918]])

In [ ]:
Counter(np.squeeze(y_test))

Counter({0: 10343,
         1: 25,
         2: 40,
         3: 91,
         4: 127,
         5: 699,
         6: 522,
         7: 1094,
         8: 1523,
         9: 968,
         10: 1282})

In [ ]:
y_pred_lat = LAT.predict(X_test)
y_pred_ord = ORD.predict(X_test)
print(y_pred_lat.shape)
print(y_pred_ord.shape)

(16714,)
(16714,)


In [ ]:
y_pred = recherche_hyper.predict(X_test)
print(y_pred.shape)

NameError: ignored

In [ ]:
Counter(y_pred_lat)

Counter({0: 16431, 1: 9, 2: 26, 3: 55, 4: 57, 5: 112, 6: 16, 7: 7, 8: 1})

In [ ]:
Counter(y_pred_ord)

Counter({1.0: 3, 2.0: 2494, 3.0: 12564, 4.0: 1630, 5.0: 22, 6.0: 1})

In [ ]:
Counter(y_pred)

Counter({0: 12654})

In [ ]:
compRes = [i for i in range(len(y_test)) if y_pred_lat[i] != y_test[i]]
print("Percentage of misclassified (LogisticAT): ", (len(compRes) / len(y_test))*100)

Percentage of misclassified (LogisticAT):  38.859638626301304


In [ ]:
compRes = [i for i in range(len(y_test)) if y_pred_ord[i] != y_test[i]]
print("Percentage of misclassified (OrdinalRidge): ", (len(compRes) / len(y_test))*100)

Percentage of misclassified (OrdinalRidge):  99.44956324039728


##### Binary ratings

In [ ]:
X_test[0:5]

array([[ 8.41378395e-01,  5.34432002e-03,  3.40197147e-01,
        -1.18576778e-01, -3.24758548e-01, -2.38113965e-02,
        -3.35352350e-01,  1.04016150e-01,  3.40260671e-01,
        -4.17731777e-02, -8.20031121e-02,  3.45330268e-02,
        -1.10753547e-01,  1.04332038e-01,  3.21296718e-01,
        -1.94437743e-01, -1.29308994e-01, -5.30655214e-02,
        -7.48823264e-04, -5.07654155e-02, -1.29433542e-01,
         1.70148045e-01,  4.20123646e-03,  5.33528333e-02,
        -6.80524978e-02,  6.83627198e-02, -1.63560440e-03,
        -1.10423756e-01, -8.89733024e-02, -2.65917353e-01,
        -9.16425771e-03,  2.75245641e-01,  1.94103780e-01,
         6.94442588e-02, -2.65887779e-01,  1.64083776e-01,
         4.03729761e-02,  6.59407891e-02, -7.93896989e-02,
         9.87779355e-02,  7.25531730e-02,  2.15577748e-01,
        -1.24880803e-01,  1.83163344e-01, -1.79910179e-02,
         2.25810615e-01, -1.25414375e-01,  1.57975170e-01,
        -2.85297222e-01, -1.25399876e-02, -2.55340377e-0

In [ ]:
Counter(np.squeeze(y_test))

Counter({0: 4691, 1: 4867})

In [ ]:
y_pred_lat = LAT.predict(X_test)
y_pred_ord = ORD.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix_lat = confusion_matrix( y_pred_lat, y_test )
print("Confusion matrix (LogisticAT) :", confusion_matrix_lat, sep = "\n")

Confusion matrix (LogisticAT) :
[[2424 2048]
 [2267 2819]]


In [ ]:
confusion_matrix_lat = confusion_matrix( y_pred_lat, y_test )
print("Confusion matrix (LogisticAT) :", 100*(confusion_matrix_lat/len(y_test)), sep = "\n")

Confusion matrix (LogisticAT) :
[[25.36095417 21.42707679]
 [23.71835112 29.49361791]]


In [ ]:
print("Percentage of misclassified (LogisticAT): ", ((confusion_matrix_lat[0,1] + confusion_matrix_lat[1,0]) / len(y_test))*100)

Percentage of misclassified (LogisticAT):  45.14542791378949


In [ ]:
confusion_matrix_ord = confusion_matrix( y_pred_ord, y_test )
print("Confusion matrix (OrdinalRidge) :", 100*(confusion_matrix_ord/len(y_test)), sep = "\n")

Confusion matrix (OrdinalRidge) :
[[25.35049173 21.48985143]
 [23.72881356 29.43084327]]


In [ ]:
print("Percentage of misclassified (OrdinalRidge): ", ((confusion_matrix_ord[0,1] + confusion_matrix_ord[1,0]) / len(y_test))*100)

Percentage of misclassified (OrdinalRidge):  45.218664992676295


# Classical regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
print(X_train[:,1:].shape)
print(X_train[:,1:][0].shape)
np.squeeze(y_train).shape

(66855, 60)
(60,)


(66855,)

In [ ]:
y = np.array([4, 23, 10, 12, 22, 35])
y.shape

(6,)

In [ ]:
print(X_test[:,1:].shape)

(12654, 60)


In [ ]:
model_LinReg = LinearRegression()
model_LinReg.fit(X_train, np.squeeze(y_train))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_lin_pred = model_LinReg.predict(X_test)

In [ ]:
def MyRound(x): 
  return math.ceil(x) if math.ceil(x) - x < x - math.floor(x) else math.floor(x)

#Counter(list(map(MyRound, y_lin_pred)))
Counter(list(map(MyRound, y_lin_pred)))

Counter({1: 3, 2: 2494, 3: 12564, 4: 1630, 5: 22, 6: 1})

In [ ]:
y_lin_pred = list(map(MyRound, y_lin_pred))
Counter(y_lin_pred)

Counter({1: 3, 2: 2494, 3: 12564, 4: 1630, 5: 22, 6: 1})

In [ ]:
compRes = [i for i in range(len(y_test)) if y_lin_pred[i] != y_test[i]]
print("Percentage of misclassified (LinearRegression): ", (len(compRes) / len(y_test))*100)

Percentage of misclassified (LinearRegression):  99.44956324039728


# Random Forest

##### Unbalanced ratings

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
modele_rf = RandomForestClassifier()

In [ ]:
modele_rf.fit(X_train, np.squeeze(y_train))	

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_predict_rf = modele_rf.predict(X_test)
Counter(y_predict_rf)	

Counter({0: 11415,
         1: 16,
         2: 45,
         3: 61,
         4: 82,
         5: 568,
         6: 479,
         7: 931,
         8: 1279,
         9: 846,
         10: 992})

In [ ]:
compRes = [i for i in range(len(y_test)) if y_predict_rf[i] != y_test[i]]
print("Percentage of misclassified (RandomForestClassifier): ", (len(compRes) / len(y_test))*100)

Percentage of misclassified (RandomForestClassifier):  54.12827569702047


##### Binary ratings

In [ ]:
modele_rf.fit(X_train, np.squeeze(y_train))	

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_predict_rf = modele_rf.predict(X_test)

In [ ]:
confusion_matrix_rf = confusion_matrix( y_predict_rf, y_test )
print("Confusion matrix (RandomForestClassifier) :", 100*(confusion_matrix_rf/len(y_test)), sep = "\n")

Confusion matrix (RandomForestClassifier) :
[[25.30864198 22.63025738]
 [23.77066332 28.29043733]]


In [ ]:
print("Percentage of misclassified (RandomForestClassifier): ", ((confusion_matrix_rf[0,1] + confusion_matrix_rf[1,0]) / len(y_test))*100)

Percentage of misclassified (RandomForestClassifier):  46.400920694706


# Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
#no convergence with default solver ’lbfgs’ (even with max_iter = 10 000)
model_LogReg = LogisticRegression(max_iter = 10000, solver = "liblinear")

In [ ]:
model_LogReg.fit(X_train, np.squeeze(y_train))	

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_predict_LogReg = model_LogReg.predict(X_test)

In [ ]:
confusion_matrix_LogReg = confusion_matrix( y_predict_LogReg, y_test )
print("Confusion matrix (LogisticRegression) :", 100*(confusion_matrix_LogReg/len(y_test)), sep = "\n")

Confusion matrix (LogisticRegression) :
[[22.33730906 19.5647625 ]
 [26.74199623 31.3559322 ]]


In [ ]:
print("Percentage of misclassified (LogisticRegression): ", ((confusion_matrix_LogReg[0,1] + confusion_matrix_LogReg[1,0]) / len(y_test))*100)

Percentage of misclassified (LogisticRegression):  46.30675873613727


# Average ratings by title

In [ ]:
val_title_mean = df_bert[["book_title", "Book-Rating"]].groupby("book_title").mean()	
Counter(list(map(MyRound, val_title_mean.values)))

Counter({0: 8165,
         1: 1039,
         2: 2355,
         3: 2813,
         4: 2288,
         5: 2047,
         6: 1146,
         7: 1344,
         8: 1504,
         9: 884,
         10: 1186})

# Test found on internet


In [ ]:
!pip install nose

     |████████████████████████████████| 163kB 22.4MB/s 


In [ ]:
import numpy as np
from scipy import stats, optimize, sparse
import mord
import functools
from nose.tools import assert_almost_equal, assert_greater_equal, assert_less

np.random.seed(0)
from sklearn import datasets, metrics, linear_model

In [ ]:
n_class = 5
n_samples = 100
n_dim = 10

In [ ]:
X = np.random.randn(n_samples, n_dim)
w = np.random.randn(n_dim)
y = X.dot(w)
bins = stats.mstats.mquantiles(y, np.linspace(0, 1, n_class + 1))
y = np.digitize(y, bins[:-1])
y -= y.min()

In [ ]:
def test_1():
    """
    Test two model in overfit mode
    """
    clf1 = mord.OrdinalRidge(alpha=0.)
    clf1.fit(X, y)

    clf2 = mord.LogisticAT(alpha=0.)
    clf2.fit(X, y)

    # the score is - absolute error, 0 is perfect
    # assert clf1.score(X, y) < clf2.score(X, y)

    clf3 = mord.LogisticSE(alpha=0.)
    clf3.fit(X, y)
    pred3 = clf3.predict(X)
    pred2 = clf2.predict(X)
    print("LogisticAT predictions \n", pred2)

    # check that it predicts better than the surrogate
    # for other loss
    assert np.abs(pred2 - y).mean() <= np.abs(pred3 - y).mean()
    # # the score is - absolute error, 0 is perfect
    # assert_almost_equal(clf.score(X, y), 0., places=2)
    #
    # clf = mord.LogisticIT(alpha=0.)
    # clf.fit(X, y)
    # # the score is classification error, 1 is perfect
    # assert_almost_equal(clf.score(X, y), 1., places=2)

    # test on sparse matrices
    X_sparse = sparse.csr_matrix(X)
    clf4 = mord.LogisticAT(alpha=0.)
    clf4.fit(X_sparse, y)
    pred4 = clf4.predict(X_sparse)
    assert metrics.mean_absolute_error(y, pred4) < 1.

In [ ]:
test_1()

LogisticAT predictions 
 [1 0 1 2 3 2 3 1 2 1 0 1 0 1 0 2 4 1 4 2 4 4 3 3 3 4 3 3 2 1 1 1 4 2 4 1 3
 4 1 0 4 4 3 0 3 2 2 0 3 0 0 4 0 2 3 1 3 0 4 2 0 4 3 0 1 1 0 1 2 4 2 2 1 0
 0 3 4 0 2 3 4 0 2 2 4 2 0 3 1 2 3 2 1 3 0 3 4 4 4 1]


In [ ]:
y

array([1, 0, 1, 2, 3, 2, 3, 1, 2, 1, 0, 1, 0, 1, 0, 2, 4, 1, 4, 2, 4, 4,
       3, 3, 3, 4, 3, 3, 2, 1, 1, 1, 4, 2, 4, 1, 3, 4, 1, 0, 4, 4, 3, 0,
       3, 2, 2, 0, 3, 0, 0, 4, 0, 2, 3, 1, 3, 0, 4, 2, 0, 4, 3, 0, 1, 1,
       0, 1, 2, 4, 2, 2, 1, 0, 0, 3, 4, 0, 2, 3, 4, 0, 2, 2, 4, 2, 0, 3,
       1, 2, 3, 2, 1, 3, 0, 3, 4, 4, 4, 1])

In [ ]:
X[0]

array([-1.00033035,  1.67398571,  0.16155927,  1.56340475, -0.79052302,
       -0.90730012,  0.22425222, -1.67868836,  0.21496559,  0.09721923])

In [ ]:
print(X.shape)
print(y.shape)

(100, 10)
(100,)


In [ ]:
Counter(y)

Counter({0: 20, 1: 20, 2: 20, 3: 20, 4: 20})